{% set name = "array-record" %}
{% set version = "0.8.0" %}
{% set sha256 = "50feb30837b6dbd6942cd059784fd81ce6dc23ff7d64f7e2a63a7c522537f6bb" %}
{% set bazel_version = "7.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/array_record/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<310]
  skip: true  # [win]
  skip: true  # [osx]

requirements:
  build:
    - python       # [target_platform != build_platform]
    - pip          # [target_platform != build_platform]
    - numpy        # [target_platform != build_platform]
    - setuptools   # [target_platform != build_platform]
    - wheel        # [target_platform != build_platform]
    - bazel 7.2.1
    - rsync
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - setuptools
    - wheel
  run:
    - python
    - etils
    - absl-py
    - numpy
    - more-itertools >=9.1.0
    - typing_extensions
    - importlib_resources
    - zipp
    - fsspec

test:
  imports:
    - array_record
  files:
    - test_array_record.py
  requires:
    - pip
    - python

about:
  home: https://pypi.org/project/array-record/
  summary: ArrayRecord file format.
  description: |
    ArrayRecord is a new file format derived from [Riegeli](https://github.com/google/riegeli),
    achieving a new frontier of IO efficiency. We designed ArrayRecord to support parallel
    read, write, and random access by record index. ArrayRecord builds on top of Riegeli
    and supports the same compression algorithms.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/google/array-record/

extra:
  recipe-maintainers:
    - iindyk
    - mtsokol
